### ISSUE TITLE
Shooter Subsystem

### ISSUE THREAD

**Issue by nix342** [frc-88/2020-Robot#10]
### **TODO**
- [X] Shooter Subsystem Analysis
- [x] Create shooter subsystem
- [x] Shooter/Intake/Hopper/Arm subsystem coordination
- [ ] Haiku

### **ACTUATORS**
* 2 Falcon500 motors for main shooter wheel
* 1 775 Pro for feeder belts

### **SENSORS**
* Falcon500 interal encoder to be used for shooter
* No encoder for feeder belts?
* ShotCountSensor
	** beam break or IR sensor to count balls leaving the shooter

Shooter Arm:
The arm will be controlled by a separate arm subsystem. The shooter will need to know what the current arm position is.

### **COMMANDS**
- [x] ShooterPrep
- [x] Shoot
- [x] ShooterStop
