### ISSUE TITLE
Climber

### ISSUE THREAD

**Issue by Evan-FRC** [frc-88/2020-Robot#23]
### **TODO**
- [x] Climber Subsystem Analysis
- [x] Create a climber subsystem
- [ ] Add climber motor encoder positions to dashboard data
- [ ] Haiku

### **ACTUATORS**
* Two Falcon500s

### **SENSORS**
* 

### **COMMANDS**
- [x] Extend Climber
- [x] Retract Climber
- [ ] Stop Climber
