### ISSUE TITLE
Arm Subsystem

### ISSUE THREAD

**Issue by nix342** [frc-88/2020-Robot#33]
Shooter Arm:
- It was discussed that there would be two positions for the shooter arm to handle different types of shots

**Components**
* 1 Falcon FX motor
    ** Each Falcon has its own encoder
* absoluteArmAngleEncoder
    ** encoder mounted below the bottom of the shooter elbow to measure the angle of the shooter. 

### **TODO**
 - [ ] haiku

### **Methods**

- [x] encoderTicksToArmDegrees
- [x] armDegreesToEncoderTicks
- [x] encoderVelocityToArmVelocity
- [x] armVelocityToEncoderVelocity
- [x] getArmPosition (angle)
- [x] setArmPosition (this uses motion magic)
- [x] moveArmPosition (this uses basic % output)

### **COMMANDS**

- [x] moveToShootingPositionOne - for shot profile 1
- [x] moveToShootingPositionTwo - for shot profile 2
- [x] moveToHomePosition - fully stowed, pregame position
- [x] moveToPosition - using motion magic
- [x] arcadeMoveToPostion - using the joystick, use basic control to move to a position - discussed for testing and calibration 
- [ ] emergencyResetArm - see safety noticed below

### **SAFETY**
If we find that we are over our buffer limit (+/- 15 degrees) then we
will stop the ARM, have the operator initiate an overide and move toward the limit switch to reset the arm (position)

**Comment by nix342** [comment]
Arm subsystem just needs a haiku.
