### ISSUE TITLE
Complete the Robot First Look/"As Built" Inspection Checklist

### ISSUE THREAD

**Issue by rbtgagnon** [frc-88/2020-Robot#35]
** First look - As Built - Inspection **

- [x] Visual inspection
- [x] Battery Check
- [x] Turn on 
- [x] Check for shorts/smoke
- [x] Check the RSL
- [x] Check CAN lights
- [x] Check RIO Lights
- [x] Check Radio
- [x] Connection to robot - (FRC Driver Station)
- [x] Check CAN IDs + Firmware
- [x] Deploy Code to Robot (Drive Branch)
- [x] Spin wheels and check encoder data
- [x] Check NavX Data
- [x] Check Limelight - updates
- [x] Visually inspect robot and verify "As Built"parts list against software robot configuration (# motors, motor types, encoder ) Record any differences with software manifest

** Robot First "drive/move" readiness** 

- [x] Robot on blocks, wheels above the ground (No contact with blocks or floor)
- [x] Operator ready to disengage robot (finger on the enter button)
- [x] Enable robot
- [x] check RSL 
- [x] Check compressors for leaks
- [x] test drive
- [x] Disable robot
- [x] Merge drive to master and prep intake branch

** Robot Intake Test **

- [x] Deploy intake branch to robot
- [x] Robot on blocks, wheels above the ground (No contact with blocks or floor)
- [x] Enable robot
- [x] check RSL 
- [x] Check compressors for leaks
- [x] test intake command
- [x] test deploy and retract commands
- [x] test run/eject/stop
- [x] test safety features
- [x] Disable robot
- [x] Merge intake branch with master

** FASH **

- [x] Catchup the FASH branch w/master
- [x] Deploy the FASH branch to the robot
- [x] Check arm sensor data
- [x] Comment out the hopper, shooter, subsystem
- [x] Note/record arm positions for full up, full down and mid (these will be turned into soft limits later
- [x] Test with basic control (check for current spikes at up and down motions)
- [x] Tune for motion magic

** Hopper + Shooter **

- [x] Deploy hopper shooter branch to robot
- [x] Robot on blocks, wheels above the ground (No contact with blocks or floor)
- [x] Test Flywheel sensor data
- [x] Test Hopper + feeder sensor data
- [x] Enable robot
- [x] Check RSL 
- [x] Test basic control of flywheel, feeder, hopper
- [x] Tune flywheel for velocity PID
- [x] Test with power cells (balls) 
- [x] Merge to master

**Comment by nix342** [comment]
It would probably be a good idea to run through this exercise again to develop our "Full System Check" checklist.
