### ISSUE TITLE
Drive

### ISSUE THREAD

**Issue by nix342** [frc-88/2020-Robot#7]
### **TODO**
- [x] Drive Subsystem Analysis
- [x] Accept outstanding pull request to pull in some of last year's code
- [x] 2x2 Falcon 500 Tank
- [x] Dashboard data
- [x] Closed loop tuning
- [x] Autonomous motion: Targeting
- [ ] Autonomous motion: Path following
- [ ] Haiku

### **ACTUATORS**
* 2xFalcon500 w TalonFX per side
* 1 double solenoid per side for shifting

### **COMMANDS**
- [x] ArcadeDrive
- [x] TankDrive
- [ ] AutoDrive
- [x] Aim

**Comment by nix342** [comment]
Work being done in Drive branch

**Comment by nix342** [comment]
2020 Drive Gearbox Ratios:
Low Gear: 18.38 : 1
High Gear: 8.50 : 1
Encoder to Wheel Ratio: 7.5 : 1
