### ISSUE TITLE
Intake Subsystem

### ISSUE THREAD

**Issue by nix342** [frc-88/2020-Robot#8]
### **TODO**
- [x] Intake Subsystem Analysis
Design of an over the bumper intake system that was discussed at the build meeting on 1/21/2020
- [x] Haiku

### **QUESTIONS**

* Will there be another roller with motor to see that the balls are kept safe in the holding area (a.k.a The Shepard) = NO

### **ASSUMPTIONS**
Actuators:
* 1 roller motor: 775pro motor, with TalonSRX controller
* one double solenoid 

Sensors:

### **COMMANDS**
- [x] Intake
- [x] Eject
- [x] Deploy
- [x] Retract
- [x] Stop

### **METHODS**
- [x] setRoller - takes value -1 to 1 and sets the roller speed based on that value.
- [x] deploy - moves the intake mechanism from its pregame starting position into the position where it can start retrieving balls. 
- [x] retract - moves the intake mechanism from its deployed position to its stowed position

**Comment by KenziePryor** [comment]
All of this is covered in the intake branch, just waiting for testing to close the issue
