### ISSUE TITLE
Storage Subsystem

### ISSUE THREAD

**Issue by nix342** [frc-88/2020-Robot#9]
### **TODO**
- [x] Storage Subsystem Analysis
- [x] Haiku

### **ACTUATORS**
- [x] 2 775 Pro motors running left and right side belts which move the balls in a holding area. The forward direction is towards the shooter and the reverse direction is towards the intake.

### **SENSORS**
- [x] Versa mag encoders on each 775.
- [ ] Camera looking at hopper to count how many are loaded 

### **COMMANDS**
- [x] Intake - runs agitators in optimal intake pattern
- [x] Shoot - runs agitators in optimal shooting pattern
- [x] Stop - stops the agitator

### **METHODS**
- [x] setAgitators (speed1, speed2)
- [ ] Power cell count - uses camera to count power cells in the hopper.

**Comment by nix342** [comment]
Work being done in storage branch
